project:
  type: book

book:
  title: "<img src='img/logo_fjp.png' alt='Logo' style='vertical-align: middle; width:180px'> Características sociais dos municípios do Vale do Lítio"
  author:
    - name: "[Caio Gonçalves](https://github.com/ccsgonc)"
      affiliation: Fundação João Pinheiro
      affiliation_url: https://fjp.mg.gov.br/
    - name: "[Vitor Marinho](https://github.com/vitor-marinho-fjp)"
      affiliation: Fundação João Pinheiro
      affiliation_url: https://fjp.mg.gov.br/
  date: "11/27/2023"
  chapters:
    - index.qmd
    - 0_intro.qmd
    - 1_Demografia.qmd
    - 2_Economia.qmd
    - 3_Social.qmd
    - 4_Ambiental.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: Sandstone
  pdf:
    documentclass: scrreprt
lang: pt
editor: visual

